version: '3.3'

services:
  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootfoobar
      MYSQL_USER: tomkooij
      MYSQL_PASSWORD: sokkenlichtkrant
      MYSQL_DATABASE: submit
    volumes:
      - ./my-data:/var/lib/mysql

  checkpy:
    image: checkpy
    build: .
    restart: unless-stopped
    environment:
      FOO: bar
    volumes:
      - '.:/base:ro'
    working_dir: '/base' 
    command: '/bin/sh'
    stdin_open: true
    tty: true
    depends_on: 
      - db

