"""add grade to Submission

Revision ID: 019228a3e107
Revises: d7865c19b871
Create Date: 2018-12-09 14:59:15.139682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019228a3e107'
down_revision = 'd7865c19b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('stored_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'stored_filename')
    op.drop_column('submission', 'score')
    # ### end Alembic commands ###
