"""add checkpy output

Revision ID: 6495980b7492
Revises: 85ecf34591d5
Create Date: 2018-12-17 09:56:08.044443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6495980b7492'
down_revision = '85ecf34591d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('checkpy_output', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('nPassed', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('nTests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'nTests')
    op.drop_column('submission', 'nPassed')
    op.drop_column('submission', 'checkpy_output')
    # ### end Alembic commands ###
