"""add category

Revision ID: 85ecf34591d5
Revises: f41fef1122ce
Create Date: 2018-12-09 15:32:19.684297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ecf34591d5'
down_revision = 'f41fef1122ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'category')
    # ### end Alembic commands ###
