"""empty message

Revision ID: d7865c19b871
Revises: 47ce7351d8d8
Create Date: 2018-12-09 09:39:44.561020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7865c19b871'
down_revision = '47ce7351d8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('submission_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'submission_filename')
    # ### end Alembic commands ###
