"""add grade to Submission

Revision ID: f41fef1122ce
Revises: 019228a3e107
Create Date: 2018-12-09 15:01:06.928315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41fef1122ce'
down_revision = '019228a3e107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('is_graded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'is_graded')
    # ### end Alembic commands ###
